# Generated by Django 4.0.2 on 2022-02-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='boolean_tags',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
