# Generated by Django 4.0.2 on 2022-02-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tags_boolean_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopetags',
            name='foreign_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.tags'),
            preserve_default=False,
        ),
    ]
