# Generated by Django 4.0.2 on 2022-02-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scopetags_foreign_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopetags',
            name='foreign_field',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='boolean_tags',
        ),
    ]
