# Generated by Django 4.0.2 on 2022-02-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_scopetags_foreign_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopetags',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='scopetags',
            name='tag_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.tags', verbose_name='Раздел'),
        ),
    ]
