# Generated by Django 4.0.2 on 2022-02-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_main_tag_scopetags_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopetags',
            old_name='tag_pk',
            new_name='name',
        ),
    ]
