# Generated by Django 4.0.2 on 2022-02-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_tag_pk_scopetags_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='scope',
        ),
    ]
