# Generated by Django 4.0.2 on 2022-02-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_scope_alter_scopetags_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopetags',
            old_name='name',
            new_name='tag',
        ),
    ]
